### PR TITLE
Ship Tier 1 & Tier 3 checklist

### PR DESCRIPTION
**Pull request by natalialuzuriaga**
## Problem

We would like to start sharing our outbound checklists for others to use and take inspiration from.

## Solution

- Shipped tier 1 checklist!
- Shipped tier 3 checklist! Other tiers coming soon!

### CODE REVIEW

**Comment by natalialuzuriaga** [comment]
Considerations:
- Do we want a separate directory to store our checklists? Or should it live in its respective tier directory?
- Would we like this converted to markdown at some point?

**Review by decause-gov — APPROVED** [review]
It's a binary file, so can't review in PR, will review in prod 😎 

🚢 ☑️ 📝

**Comment by decause-gov** [comment]
> Considerations:
> 
>     * Do we want a separate directory to store our checklists? Or should it live in its respective tier directory?
> 
>     * Would we like this converted to markdown at some point?

1. Ship it in the Tier folder it corresponds to for now.
2. Plz open a ticket to convert to Tier3 checklist to .md file.

**Comment by natalialuzuriaga** [comment]
Issues have been created to convert to markdown file: #68 + #69
 
Waiting on input from Elizabeth and Dave before shipping

**Comment by natalialuzuriaga** [comment]
LGTM from Elizabeth!

**Pull request merged**
