### PR TITLE
Fixed laborHours Calculations

### PR DESCRIPTION
**Pull request by sachin-panayil**
## Problem

Overall, labor_hour value is pretty high because it is taking into account the markdown files. We would like to exclude this from the calculation.

## Solution

Included a flag in the scc command that excludes md files.

## Result

A decrease in laborHours

### Before
Screenshot 2024-11-07 at 5 22 28 PM

### After
Screenshot 2024-11-07 at 5 20 34 PM

Some important notes regarding the summary line:

* Issue #196 
* We can add more files that we want to exclude to fine tune this

## Test Plan

Tested locally and each tier showed a decrease in labor hours

### CODE REVIEW

**Review by IsaacMilarky — CHANGES_REQUESTED** [review]
I think this is on the right track but I think we should be more specific in what we exclude. 

scc supports adding a `.sccignore` file in the same way that `.gitignore` works: https://github.com/boyter/scc?tab=readme-ov-file#ignore-files

Preferably, we would exclude all changes before a specific commit or something but I don't think that that is supported by scc.

**Comment by sachin-panayil** [comment]
@IsaacMilarky one of my approaches was to use the .sccignore file but for some reason the laborHours value wasnt changing. I will take another crack at it tho using .sccignore incase i used it improperly. 

if the above issue persists then maybe we can have an array of files we want to exclude and pipe that into the command with the current method

**Review by IsaacMilarky — CHANGES_REQUESTED** [review]
Can we use the `--exclude-file` option instead of the `--exclude-ext` option? That way we won't exclude all of the additional docs work a project is doing. It's good to know if a project is providing docs and analyze the work in that. 

If there are problems with that option we can talk about it more this week.

**Comment by sachin-panayil** [comment]
this new method reduces laborHour bloat significantly

**Review by IsaacMilarky — APPROVED** [review]
LGTM 👍

**Pull request merged**
